"config/dynamics.xml":
  class: sfDynamicsConfigHandler
  file:  <?php echo realpath(dirname(__FILE__).'/../lib/config/handler'); ?>/sfDynamicsConfigHandler.class.php

"modules/*/config/view.yml":
  class: sfDynamicsViewConfigHandler
  file:  <?php echo realpath(dirname(__FILE__).'/../lib/config/handler'); ?>/sfDynamicsViewConfigHandler.class.php

